FORMAT: 1A
HOST: http://sample.com.br/api/v1

# BossaBox API

> With this service you can list, add, delete and search all your tools.

The service meets the **BossaBox** challenge specification and you can register all the tools you want</br>
**ENJOY!**


# Group Tools

## List and Create [/tools]

### List all [GET]

+ Response 200 (application/json)

    + Body

            [
                {
                    "_id": "5cdb4c24b459ff2013cbae01",
                    "title": "Notion",
                    "link": "https://notion.so",
                    "description": "All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ",
                    "tags": [
                        "organization",
                        "planning",
                        "collaboration",
                        "writing",
                        "calendar"
                    ]
                },
                {
                    "_id": "5cdb4c24b459ff2013cbae22",
                    "title": "json-server",
                    "link": "https://github.com/typicode/json-server",
                    "description": "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
                    "tags": [
                        "api",
                        "json",
                        "schema",
                        "node",
                        "github",
                        "rest"
                    ]
                },
                {
                    "_id": "5cdb4c24b459ff2013cbae52",
                    "title": "fastify",
                    "link": "https://www.fastify.io/",
                    "description": "Extremely fast and simple, low-overhead web framework for NodeJS. Supports HTTP2.",
                    "tags": [
                        "web",
                        "framework",
                        "node",
                        "http2",
                        "https",
                        "localhost"
                    ]
                }
            ]


### Add new tool [POST]

+ Request  (application/json)

    + Body

            {
                "title": "hotel",
                "link": "https://github.com/typicode/hotel",
                "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
                "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
            }

+ Response 200 (application/json)

    + Body

            {
                "_id": "5cdb4c24b459ff2013cbae59",
                "title": "hotel",
                "link": "https://github.com/typicode/hotel",
                "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
                "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
            }

## Filter [/tools{?tag}]

+ Parameters
    + tag: node (string, optional) - Use `tag` to filter tools.

### Filter by tag [GET]

+ Response 200 (application/json)

    + Body

            [
                {
                    "_id": "5cdb4c24b459ff2013cbae59",
                    "title": "json-server",
                    "link": "https://github.com/typicode/json-server",
                    "description": "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
                    "tags": [
                        "api",
                        "json",
                        "schema",
                        "node",
                        "github",
                        "rest"
                    ]
                },
                {
                    "_id": "5cdb4c24b459ff2013cbae51",
                    "title": "fastify",
                    "link": "https://www.fastify.io/",
                    "description": "Extremely fast and simple, low-overhead web framework for NodeJS. Supports HTTP2.",
                    "tags": [
                        "web",
                        "framework",
                        "node",
                        "http2",
                        "https",
                        "localhost"
                    ]
                }
            ]

+ Response 404 (application/json)

    + Body

            {
                "status": 404,
                "message": "No tool found"
            }

## Pass ID [/tools/{id}]

+ Parameters
    + id: 5cdb4c24b459ff2013cbae59 (string) - The `id` of tool.

### List tool [GET]

+ Response 200 (application/json)

    + Body

            {
                "_id": "5cdb4c24b459ff2013cbae59",
                "title": "json-server",
                "link": "https://github.com/typicode/json-server",
                "description": "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
                "tags": [
                    "api",
                    "json",
                    "schema",
                    "node",
                    "github",
                    "rest"
                ]
            }

+ Response 404 (application/json)

    + Body

            {
                "status": 404,
                "message": "No tool found by id"
            }

### Update tool [PUT]
+ Request  (application/json)

    + Body

            {
                "title": "hotel", // required
                "link": "https://github.com/typicode/hotel", // required
                "description": "",
                "tags":[]
            }

+ Response 200 (application/json)

    + Body

            {
                "status": 200,
                "message": "Tool updated successfully"
            }

### Delete tool [DELETE]

+ Response 200 (application/json)

    + Body

            {}
